# Generated by Django 3.0.7 on 2020-11-09 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField(blank=True, null=True)),
                ('comment_time', models.TimeField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('call_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('call_status', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_detail', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstphone', models.CharField(blank=True, max_length=100, null=True)),
                ('secondphone', models.CharField(blank=True, max_length=100, null=True)),
                ('thirdphone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=10000, null=True)),
                ('details', models.CharField(blank=True, max_length=20000, null=True)),
                ('firsttag', models.CharField(blank=True, max_length=100, null=True)),
                ('secondtag', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('assignedto_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dateadded', models.DateField(blank=True, null=True)),
                ('first_comment_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('due_date_time', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('Talk_Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_Dial', models.CharField(blank=True, max_length=100, null=True)),
                ('Unique_Dial', models.CharField(blank=True, max_length=100, null=True)),
                ('Connected_Call', models.CharField(blank=True, max_length=100, null=True)),
                ('First_Call', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Call', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('Leads_Assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('Leads_Declined', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('working_status', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_provider', models.CharField(default='google', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
